/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {
    public boolean getGreeting() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("hii");
    }
}
